uv run accelerate launch run_test.py \
    --model_name_or_path "google/gemma-2-2b" \
    --steering_coeffs 350 350 \
    --alpha 300 300 \
    --layer_id 9 \
    --max_num_batches 250 \
    --batch_size 4 \
    --type "original" \
    --gradient_checkpointing \
    --gradient_accumulation_steps 1 \
    --noverbose; \